### ISSUE TITLE
Preferred overhangs

### ISSUE THREAD

**Issue by Sum02dean** [Edinburgh-Genome-Foundry/GoldenHinges#1]
Hello! I am having difficulty attempting to provide a set of overhangs to the selector object. 
I have two sets of overhangs. Prioritized as set1 and set2. I want to attempt a cutting solution with only overhangs chosen either from set1 (priority) or set2,  as such: 

```python
from goldenhinges import OverhangsSelector
from goldenhinges.reports import write_report_for_cutting_solution

#define goldenHinges vars
# Overhang sets
set1 = ['CCCT', 'AACG','ATCG','GCTG', 
        'TACA','GAGT','CCGA']

set2 = ['AGTG','CAGG', 'ACTC', 'AAAA', 'AGAC', 'CGAA', 'ATAG', 'AACC', 'TACA',
        'TAGA', 'ATGC', 'GATA', 'CTCC', 'GTAA', 'CTGA', 'ACAA', 
        'AGGA', 'ATTA' , 'ACCG', 'GCGA']


all_preferred = {'set1':set1,'set2': set2}
# List of forbidden 4bp overhangs
forbidden = {"eColi":["TATG", "TGAG"],
             "mam/ins": ["CCAT", "TGAT"]}
#define criteria
gc_min = 0.25
gc_max = 0.75
differences =  2
forbidden_overhangs = forbidden['mam/ins'] 

#define default selector
selector = OverhangsSelector(gc_min=gc_min, gc_max=gc_max, differences=differences)

#search for  overhangs from set 1 else try from set2
for key, value in all_preferred.items():
    #append the set to selector overhangs (something not correct here)
    print(value)
    selector.all_overhangs = value
    print(selector.all_overhangs)
    solution = selector.cut_sequence(record, allow_edits=False, include_extremities=False)
    if solution != None:
        break
```
This gives:

---------------------------------------------------------------------------

['CCCT', 'AACG', 'ATCG', 'GCTG', 'TACA', 'GAGT', 'CCGA']
['CCCT', 'AACG', 'ATCG', 'GCTG', 'TACA', 'GAGT', 'CCGA']

> IndexError                                Traceback (most recent call last)
> <ipython-input-25-f0779cb9bd1f> in <module>
>      16     selector.all_overhangs = value
>      17     print(selector.all_overhangs)
> ---> 18     solution = selector.cut_sequence(record, allow_edits=False, include_extremities=False)
>      19     if solution != None:
>      20         break
> 
> ~/miniconda3/envs/keras2/lib/python3.6/site-packages/goldenhinges/OverhangsSelector.py in cut_sequence(self, sequence, intervals, solutions, allow_edits, include_extremities, optimize_score, edit_penalty, equal_segments, max_radius, target_indices)
>     460             return None
>     461         choices = self.select_from_sets(sets_list, solutions=solutions,
> --> 462                                         optimize_score=optimize_score)
>     463 
>     464         def get_solution(choices):
> 
> ~/miniconda3/envs/keras2/lib/python3.6/site-packages/goldenhinges/OverhangsSelector.py in select_from_sets(self, sets_list, solutions, optimize_score)
>     223 
>     224         if solutions == 1:
> --> 225             returned = get_solution()
>     226             solver.delete()
>     227             return returned
> 
> ~/miniconda3/envs/keras2/lib/python3.6/site-packages/goldenhinges/OverhangsSelector.py in get_solution()
>     220                 return None
>     221             else:
> --> 222                 return [self.all_overhangs[v.get_value()] for v in variables]
>     223 
>     224         if solutions == 1:
> 
> ~/miniconda3/envs/keras2/lib/python3.6/site-packages/goldenhinges/OverhangsSelector.py in <listcomp>(.0)
>     220                 return None
>     221             else:
> --> 222                 return [self.all_overhangs[v.get_value()] for v in variables]
>     223 
>     224         if solutions == 1:
> 
> IndexError: list index out of range

Is there another way to achieve this?

Thanks in advance.

**Comment by Zulko** [comment]
I don't think you can change ``selector.all_overhangs`` "on the fly", you need to provide the set of possible overhangs when you initialize the selector, and in your case that would be inside the ``for`` loop:

```python
from goldenhinges import OverhangsSelector
from goldenhinges.reports import write_report_for_cutting_solution

#define goldenHinges vars
# Overhang sets
set1 = ['CCCT', 'AACG','ATCG','GCTG', 
        'TACA','GAGT','CCGA']

set2 = ['AGTG','CAGG', 'ACTC', 'AAAA', 'AGAC', 'CGAA', 'ATAG', 'AACC', 'TACA',
        'TAGA', 'ATGC', 'GATA', 'CTCC', 'GTAA', 'CTGA', 'ACAA', 
        'AGGA', 'ATTA' , 'ACCG', 'GCGA']


all_preferred = {'set1':set1,'set2': set2}
# List of forbidden 4bp overhangs
forbidden = {"eColi":["TATG", "TGAG"],
             "mam/ins": ["CCAT", "TGAT"]}
#define criteria
gc_min = 0.25
gc_max = 0.75
differences =  2
forbidden_overhangs = forbidden['mam/ins'] 

#search for  overhangs from set 1 else try from set2
for set_name, possible_overhangs in all_preferred.items():
    selector = OverhangsSelector(
        gc_min=gc_min, gc_max=gc_max,
        differences=differences,
        possible_overhangs=possible_overhangs,
        forbidden_overhangs=forbidden_overhangs
     )
    solution = selector.cut_sequence(record, allow_edits=False, include_extremities=False)
    if solution != None:
        break
```

**Comment by Sum02dean** [comment]
Excellent thank you for the quick reply. 
It worked perfectly. I will close the issue.

thanks again.

**Comment by Zulko** [comment]
Cool, let me know if you have other troubles/questions in the future.
