### ISSUE TITLE
include_extremities=True returns decomposed sequences that do not include the exact 4-bp termini

### ISSUE THREAD

**Issue by Onejrussell-Zymergen** [Edinburgh-Genome-Foundry/GoldenHinges#3]
The result shows terminal cut sites a couple of bases offset from either end of the original sequence. Is there a way to force the terminal overhangs to be the exact first and last 4-bp sequences?
[summary_plot.pdf](https://github.com/Edinburgh-Genome-Foundry/GoldenHinges/files/5593677/summary_plot.pdf)

**Comment by Zulko** [comment]
`include_extremities` is meant to include the termini, [with no wiggle room](https://github.com/Edinburgh-Genome-Foundry/GoldenHinges/blob/master/goldenhinges/OverhangsSelector.py#L426), and haven't met a problem with it before (do you have an example you could share?)

**Comment by Onejrussell-Zymergen** [comment]
Thanks for your reply. Here is an example sequence that I'm having issues
with. If I submit this through the web UI tool, I get the following result
without include extremities:
*Program error: cannot convert float NaN to integer*

With include extremities:

*No solution found 😢. Maybe your parameters are too restrictive ?*

When I run this on my own with a set of predefined overhangs, I get an
empty list of cut sites returned.

permitted_overhangs
= ['TGCC','GCAA','ACTA','TTAC','CAGA','TGTG','GAGC','AGGA','ATTC','CGAA','ATAG','AAGG','AACT','AAAA','ACCG','ACGG','CGTT','TGAT','AATG','GTCT','ACAC','CTCG','TCCT','TAAG','GCTT','TATC','TTCC','TTGA','TTTT','TGGC','TAAC','AGCT']

selector = OverhangsSelector(gc_min=0, gc_max=1, differences=1,
forbidden_overhangs=[], possible_overhangs=permitted_overhangs)
cut_sites = selector.cut_sequence(complete_seq, equal_segments=2,
max_radius=50, include_extremities=True, optimize_score=True)

TAACGGTACAGTAAGTGAGAATCCCTATCAGTGATAGGGATCCCTATCAGTGATAGGTCGACCTATCAGTGATAGTTAATTAACTTGTAATATTCTAATCAAGCTCGCCCCAAGAGAGCTGAAGATGCTGAGTAGGGTTGTCCAGGCAGCACATATATAAGATGCTTCGTCCCCTCCCATCGAGTCCTTCTTTTCTCTCTCTCATCAATCACTCTACTTCCTACTCTACCTTAAACTCTTCACTACTTCATACATTAATTAAAATGACTGCCCTTACTGAAGGCGCAAAATTATTCGAAAAAGAAATTCCTTATATAACCGAACTGGAAGGAGACGTGGAGGGCATGAAGTTTATCATTAAGGGCGAGGGAACAGGCGACGCAACCACTGGCACCATAAAGGCAAAGTATATCTGTACTACTGGAGATTTGCCCGTGCCCTGGGCCACTCTAGTGTCAACGTTGTCATATGGAGTACAATGTTTCGCCAAGTATCCATCTCACATAAAAGATTTCTTCAAGAGTGCCATGCCTGAGGGTTATACTCAAGAACGTACTATAAGTTTTGAGGGAGATGGCGTTTATAAAACTAGAGCCATGGTGACTTATGAGAGGGGTAGTATTTACAATAGAGTTACACTGACTGGTGAAAACTTCAAAAAGGATGGACACATTTTGAGGAAAAATGTTGCCTTTCAATGTCCTCCCTCCATCCTTTACATTTTACCCGACACAGTCAACAATGGCATCAGAGTAGAATTCAACCAAGCCTATGACATAGAAGGAGTGACGGAAAAATTGGTCACTAAGTGCTCACAGATGAACAGACCTTTGGCTGGCTCAGCAGCCGTACACATACCTAGATACCATCATATCACTTATCACACGAAACTATCCAAAGATAGAGACGAGAGGCGTGATCATATGTGTCTTGTCGAGGTGGTTAAAGCAGTAGACTTAGACACGTACCAGTAAGTCGACATGGAACAGAAGTTGATTTCCGAAGAAGACCTCGAGTAAGCTTGGTACCGCGGCTAGCTAAGATCCGCTCTAACCGAAAAGGAAGGAGTTAGACAACCTGAAGTCTAGGTCCCTATTTATTTTTTTATAGTTATGTTAGTATTAAGAACGTTATTTATATTTCAAATTTTTCTTTTTTTTCTGTACAGACGCGTGTACGCATGTAACATTATACTGAAAACCTTGCTTGAGAAGGTTTTGGGACGCTCGAAGGACTCTGTACTGAGTTCTATAAACGAGCCATTGCATACGAGATCGGTAGATTGATAAGGGACACAGAATATCCCCGGACGCAATAGACGGACAGCTTGGTATCCTAAGCACAGTCGCGCGTCCGAACCTAGCTCTACTTTAGAGGCCCCGGATTCTGGTGCTCGTAGACCGCAGAACCGATTGGGGGGATGTACAACAATATTTGTTAGTCACCTTTGGGTCACGATCTCCCACCTTACTGGAATTTAGTCCCTGCTATAATTTGCCTTGCATATAAGTTGCGTTACTTCAGCGTCCTAACCGCACCCTTAGCACGAAGACAGATTTGTTAATTCCCTTACTCCGGCGTTGGCAGGGGGTTCGTATGTCCCACGTGAAACGTTGCTAAACCCTCAGGTTTAGCT

One time I ran this or a very similar sequence (same extremities) through
the web UI and got the attached image as a result. I can't remember the
exact parameters I used, but the overhangs on the ends should be TAAC or
AGCT.

Thanks for your help,
James

**Comment by veghp** [comment]
I can confirm that CUBA's [design overhangs app](https://cuba.genomefoundry.org/design-overhangs) returns no results using your sequence and permitted overhangs. The real issue is that AGCT is a palindromic overhang, so it will anneal with itself. You can check your overhang sets with [CUBA's view overhangs crosstalk app](https://cuba.genomefoundry.org/view-overhangs-crosstalk).

**Comment by Onejrussell-Zymergen** [comment]
Hi,
Thanks for pointing this out.

Best,
James
